fun main() {
    println("Running Day 1")
    day1()
    println("Running Day 2")
    day2()
    println("Running Day 3")
    day3()
    println("Running Day 6")
    day6()
    println("Running Day 7")
    day7()
    println("Running Day 8")
    day8()
    println("Running Day 14")
    day14()
}
